### ISSUE TITLE
[Modificación de resultados] - PopulateDatabase.java

### ISSUE THREAD

**Issue by davalvsil** [EGC-1415-Repositorio-compartido/repvoting#26]
Buenas,

Tenemos un problema con la línea 42 de vuestro PopulateDatabase.java

populationContext = new ClassPathXmlApplicationContext("classpath:populateDatabase.xml");

Ya que usamos una máquina Ubuntu que al parecer hace distinción entre mayúsculas y minúsculas en el nombre de los ficheros, por lo que no coge bien vuestro XML, ya que dicho XML se llama PopulateDatabase.xml.

Por lo que nos vendría bien que la cambiaseis poniendo:

populationContext = new ClassPathXmlApplicationContext("classpath:PopulateDatabase.xml");

Gracias y un saludo.

**Comment by abayta** [comment]
No hace falta que ejecutéis el PopulateDatabase.java para que el proyecto funcione, solo necesita que este creada la base de datos.

De todas formas estoy trabajando para solucionar errores como este y posiblemente el proyecto en si cambie mucho sin que esto afecte a la API que ofrecemos.

**Comment by antoniojuanamador** [comment]
Pero para crear la base de datos lo hacemos desde ese fichero, si no os cuesta mucho trabajo y dado que a nadie le causaría problemas, ¿Podríais cambiarlo?

**Comment by abayta** [comment]
Acabo de subir una nueva versión en la que ya no hace falta crear la base de datos ni generar un .war. Las instrucciones para desplegarlo estan aqui: https://github.com/EGC-1415-Repositorio-compartido/repvoting/tree/master/results
