### ISSUE TITLE
No hay una votación cifrada de ejemplo.

### ISSUE THREAD

**Issue by abayta** [EGC-1415-Repositorio-compartido/repvoting#27]
Si no hay ninguna votación de ejemplo con votos cifrados, claves disponibles, etc. Los subprogramas de resultados y modificación de resultados no podemos ir probando nuestra funcionalidad y por lo tanto nuestro desarrollo será totalmenta a ciegas.

**Comment by juamaiosu** [comment]
En la base de datos de almacenamiento hay votos cifrados lo que pasa que también hay votos desde que empezamos sin cifrar. Tenemos que ponernos de acuerdo todos para que almacenamiento limpie la base de datos y empecemos de nuevo a meter votos cifrados.

**Comment by juamaiosu** [comment]
Al final se ha eliminado de la base de datos de almacenamiento todos los votos y se ha insertado votos cifrados validos.

![img-20150111-wa0008](https://cloud.githubusercontent.com/assets/9355685/5695228/a149db8c-9996-11e4-99a6-f8cf46b81bea.jpg)
