### ISSUE TITLE
Recuento: error: unmappable character for encoding UTF8

### ISSUE THREAD

**Issue by juamaiosu** [EGC-1415-Repositorio-compartido/repvoting#29]
Hola estoy creando el .war por Jenkins y me sale el siguiente error:

![seleccion_014](https://cloud.githubusercontent.com/assets/9355685/5803281/48194850-9ffd-11e4-8b8d-26fe05833097.png)

El motivo es por las tildes o eso creo.

Gracias y saludos.

**Comment by darkspartan** [comment]
¿Has probado a usar la codificación ISO-8859-1 en vez de UTF-8?

**Comment by juamaiosu** [comment]
Como puedo cambiarlo?

**Comment by juamaiosu** [comment]
gracias a un compañero de Recuento (Juan) que ha modificado las tildes, se ha solucionado el problema. 

Gracias.
